spring.application.name=mysqlDB

spring.datasource.url=jdbc:mysql://sql306.infinityfree.com:3306/if0_41047229_conectar
spring.datasource.username=if0_41047229
spring.datasource.password=qzOFJ8bDzEw4D2
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver